BanHang/Controllers/NhaCungCapController.cs
using BanHang.Common;
using Model.DAO;
using Model.EF;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class NhaCungCapController : BaseController
    {
        // GET: NhaCungCap
        [KiemTraQuyen(MaChucNang = "Xem_NhaCungCap")]
        public ActionResult Index(string search, int page = 1, int pagesize = 10)
        {
            var dao = new NCCDAO();
            var model = dao.ListAllPaging(search, page, pagesize);
            ViewBag.Search = search;
            return View(model);
        }


        [HttpGet]
        public ActionResult ThemMoi()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult CapNhat(long id)
        {
            var nhaCungCap = new NCCDAO().ViewDetail(id);
            return PartialView(nhaCungCap);
        }

        [HttpGet]
        public ActionResult Xoa(long id)
        {
            var nhaCungCap = new NCCDAO().ViewDetail(id);
            return PartialView(nhaCungCap);
        }

        [HttpGet]
        public ActionResult ThongTin(long id)
        {
            var nhaCungCap = new NCCDAO().ViewDetail(id);
            return PartialView(nhaCungCap);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemMoi(NhaCungCap nhaCungCap)
        {
            var dao = new NCCDAO();
            long id = dao.Insert(nhaCungCap);
            if (id > 0)
            {
                SetAlert("Thêm thành công", "success");
                return RedirectToAction("Index");
            }
            else
            {
                SetAlert("Thêm thất bại", "error");
            }
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CapNhat(NhaCungCap nhaCungCap)
        {
            var dao = new NCCDAO();
            var id = dao.Update(nhaCungCap);
            if (id)
            {
                SetAlert("Cập nhật thành công", "error");
                return RedirectToAction("Index");
            }
            return View("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Xoa(NhaCungCap nhaCungCap)
        {
            var dao = new NCCDAO();
            var id = dao.Delete(nhaCungCap);
            if (id)
            {
                SetAlert("Xóa thành công", "error");
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        public void Ds_NhaCungCap()
        {
            OnlineShopDbContext db = new OnlineShopDbContext();
            var model = db.NhaCungCaps.ToList();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var Ep = new ExcelPackage(new FileInfo("NhaCungCap.xlsx")))
            {
                ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
                Sheet.Cells["A1"].Value = "Mã NCC";
                Sheet.Cells["B1"].Value = "Tên";
                Sheet.Cells["C1"].Value = "Số điện thoại";
                Sheet.Cells["D1"].Value = "Địa chỉ";
                Sheet.Cells["E1"].Value = "Email";
                Sheet.Cells["F1"].Value = "Mã thuế";
                Sheet.Cells["G1"].Value = "Ghi Chú";
                int row = 2;
                foreach (var item in model)
                {

                    Sheet.Cells[string.Format("A{0}", row)].Value = item.MaNCC;
                    Sheet.Cells[string.Format("B{0}", row)].Value = item.TenNCC;
                    Sheet.Cells[string.Format("C{0}", row)].Value = item.SoDT;
                    Sheet.Cells[string.Format("D{0}", row)].Value = item.DiaChi;
                    Sheet.Cells[string.Format("E{0}", row)].Value = item.Email;
                    Sheet.Cells[string.Format("F{0}", row)].Value = item.MaThue;
                    Sheet.Cells[string.Format("G{0}", row)].Value = item.GhiChu;
                    row++;
                }


                Sheet.Cells["A:AZ"].AutoFitColumns();
                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment: filename=" + "NhaCungCap.xlsx");
                Response.BinaryWrite(Ep.GetAsByteArray());
                Response.End();
            }

        }

    }
}

BanHang/Views/NhaCungCap/CapNhat.cshtml
@model Model.EF.NhaCungCap

@{
    Layout = null;
}

@using (Html.BeginForm("CapNhat", "NhaCungCap", FormMethod.Post))
{
    <div class="modal-header bg-maroon">
        <h4 class="modal-title">Cập nhật thông tin</h4>
    </div>

    <div class="modal-body form-horizontal">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MaNCC)

        <div class="form-group">
            @Html.LabelFor(model => model.TenNCC, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenNCC, new { @class = "form-control", required = "required" })   
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDT, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.SoDT, new { @class = "form-control", type = "number", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", type = "email", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaThue, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.MaThue, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.GhiChu, new { @class = "form-control", rows = "5", cols = "20" })
            </div>
        </div>

        <div class="modal-footer">
            <div class="clearfix text-right">
                <button type="submit" class="btn bg-maroon btn-lg">Cập nhật</button>
                @Html.ActionLink("Đóng", "Index", null, new { @class = "btn btn-default btn-lg", onclick = "return confirm('Các thay đổi sẽ không được cập nhật. Bạn vẫn muốn trở về danh sách?');" })
            </div>
        </div>
    </div>
}

BanHang/Views/NhaCungCap/Index.cshtml
@model PagedList.IPagedList<Model.EF.NhaCungCap>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Danh sách nhà cung cấp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1 class="page-header">
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Tác vụ</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>


<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                <div>
                    <a href="@Url.Action("Ds_NhaCungCap","NhaCungCap")" class=" btn btn-primary btn-lg pull-right">
                        Xuất Excel
                    </a>
                    <a href="@Url.Action("ThemMoi","NhaCungCap")" class="btn bg-olive btn-lg" data-toggle="modal" data-target="#modal-themMoi" data-backdrop="static" data-keyboard="false">
                        Thêm Mới
                    </a>
                    <div class="modal fade " id="modal-themMoi">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                @using (Html.BeginForm("Index", "NhaCungCap", FormMethod.Get))
                {
                    <div class="input-group">
                        <input type="text" name="search" value="@ViewBag.Search" class="form-control" placeholder="Tìm kiếm theo Tên">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                }
                <br />
                <table id="example2" class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="background-color:#80d6ff; font-size : 15px; text-align: center">Mã NCC</th>
                            <th style="background-color: #80d6ff; font-size: 15px; text-align: center">Tên nhà cung cấp</th>
                            <th style="background-color:#80d6ff; font-size : 15px; text-align: center">Số điện thoại</th>
                            <th style="background-color:#80d6ff; font-size : 15px; text-align: center">Email</th>
                            <th style="background-color:#80d6ff; font-size : 15px; text-align: center">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td style="padding-top: 12px;text-align: center">@item.MaNCC</td>
                            <td style="padding-top: 12px;text-align: center">@item.TenNCC</td>
                            <td style="padding-top: 12px;text-align: center">+84 @item.SoDT</td>
                            <td style="padding-top: 12px;text-align: center">@item.Email</td>
                            <td class="text-center">
                                <a href="/NhaCungCap/ThongTin/@item.MaNCC" class="btn bg-purple" style="border-radius: 15px" data-toggle="modal" data-target="#modal-thongTin-@item.MaNCC" data-backdrop="static" data-keyboard="false">Chi tiết</a>
                                <div class="modal fade " id="modal-thongTin-@item.MaNCC">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                        </div>
                                    </div>
                                </div>
                                <a href="/NhaCungCap/CapNhat/@item.MaNCC" class="btn bg-maroon" style="border-radius: 15px" data-toggle="modal" data-target="#modal-capNhat-@item.MaNCC" data-backdrop="static" data-keyboard="false">Sửa</a>
                                <div class="modal fade " id="modal-capNhat-@item.MaNCC">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                        </div>
                                    </div>
                                </div>
                                <a href="/NhaCungCap/Xoa/@item.MaNCC" class="btn bg-navy" style="border-radius: 15px" data-toggle="modal" data-target="#modal-Xoa-@item.MaNCC">Xóa</a>
                                <div class="modal fade " id="modal-Xoa-@item.MaNCC">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page, @search = ViewBag.Search }))
            </div>
        </div>
    </div>
</div>

BanHang/Views/NhaCungCap/ThemMoi.cshtml
@model Model.EF.NhaCungCap

@{
    Layout = null;
}


@using (Html.BeginForm("ThemMoi", "NhaCungCap", FormMethod.Post))
{
    <div class="modal-header bg-olive">
        <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Thêm nhà cung cấp</h4>
    </div>

    <div class="modal-body form-horizontal">

        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.TenNCC, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenNCC, new { @class = "form-control", required = "required" })           
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoDT, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.SoDT, new { @class = "form-control", type = "number", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.DiaChi, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", type = "email", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaThue, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.MaThue, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GhiChu, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextAreaFor(model => model.GhiChu, new { @class = "form-control", rows = "5", cols = "20" })
            </div>
        </div>

        <div class="modal-footer">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn bg-olive btn-lg">Thêm Mới</button>
            </div>
        </div>
    </div>
}

BanHang/Views/NhaCungCap/ThongTin.cshtml
@model Model.EF.NhaCungCap

@{
    Layout = null;
}

<div class="modal-header bg-purple">
    <h4 class="modal-title">Thông tin nhà cung cấp</h4>
</div>

<div class="modal-body dl-horizontal">
    <table class="table table-striped table-bordered ">
        <tr>
            <td>@Html.DisplayNameFor(model => model.TenNCC)</td>
            <td align="left">@Html.DisplayFor(model => model.TenNCC)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.SoDT)</td>
            <td align="left">+84 @Html.DisplayFor(model => model.SoDT)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.DiaChi)</td>
            <td align="left">@Html.DisplayFor(model => model.DiaChi)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.Email)</td>
            <td align="left">@Html.DisplayFor(model => model.Email)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.MaThue)</td>
            <td align="left">@Html.DisplayFor(model => model.MaThue)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.GhiChu)</td>
            <td align="left">@Html.DisplayFor(model => model.GhiChu)</td>
        </tr>
    </table>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Đóng</button>
</div>

BanHang/Views/NhaCungCap/Xoa.cshtml
@model Model.EF.NhaCungCap

@{
    Layout = null;
}

@using (Html.BeginForm("Xoa", "NhaCungCap", FormMethod.Post))
{
    <div class="modal-header bg-navy">
        <h4 class="modal-title">Xóa nhà cung cấp</h4>
    </div>

    <div class="modal-body">
        <!-- form start -->
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MaNCC)
        <h4>Bạn có chắc muốn xoá nhà cung cấp này?</h4>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-lg bg-navy">Xóa</button>
    </div>
}