BanHang/Controllers/LoaiSanPhamController.cs
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BanHang.Common;
using BanHang.Models;

namespace BanHang.Controllers
{
    public class LoaiSanPhamController : BaseController
    {
        // GET: LoaiSanPham
        [KiemTraQuyen(MaChucNang = "Xem_PhanLoai")]
        public ActionResult Index(int page = 1, int pagesize = 10)
        {
            var dao = new LoaiSanPhamDAO();
            var model = dao.ListAllPaging(page, pagesize);
            return View(model);
        }

        [HttpGet]
        public ActionResult ThemMoi()
        {
            var dao = new DrownList();
            ViewBag.MaNCC = new SelectList(dao.ListNCC(), "MaNCC", "TenNCC");
            return PartialView();
        }

        [HttpGet]
        public ActionResult CapNhat(long id)
        {
            var loaiSP = new LoaiSanPhamDAO().ViewDetail(id);
            return PartialView(loaiSP);
        }

        [HttpGet]
        public ActionResult Xoa(long id)
        {
            var loaiSP = new LoaiSanPhamDAO().ViewDetail(id);
            return PartialView(loaiSP);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemMoi(LoaiSanPham loaiSP)
        {
            var dao = new LoaiSanPhamDAO();
            long id = dao.Insert(loaiSP);
            if (id > 0)
            {
                SetAlert("Thêm thành công", "success");
                return RedirectToAction("Index");
            }
            else
            {
                SetAlert("Thêm thất bại", "error");
            }
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CapNhat(LoaiSanPham loaiSP)
        {
            var dao = new LoaiSanPhamDAO();
            var id = dao.Update(loaiSP);
            if (id)
            {
                SetAlert("Cập nhật thành công", "error");
                return RedirectToAction("Index");
            }
            return View("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Xoa(LoaiSanPham loaiSP)
        {
            var dao = new LoaiSanPhamDAO();
            var id = dao.Delete(loaiSP);
            if (id)
            {
                SetAlert("Xóa thành công", "error");
                return RedirectToAction("Index");
            }
            else
                return View();
        }
    }
}

BanHang/Views/LoaiSanPham/CapNhat.cshtml
@model Model.EF.LoaiSanPham

@{
    Layout = null;
}

@using (Html.BeginForm("CapNhat", "LoaiSanPham", FormMethod.Post))
{
    <div class="modal-header bg-maroon">
        <h4 class="modal-title">Cập nhật</h4>
    </div>

    <div class="modal-body form-horizontal">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.MaLoaiSP)

        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenLoai, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="modal-footer">
            <div class="clearfix text-right">
                <button type="submit" class="btn bg-maroon btn-lg">Cập nhật</button>
                @Html.ActionLink("Đóng", "Index", null, new { @class = "btn btn-default btn-lg", onclick = "return confirm('Các thay đổi sẽ không được cập nhật. Bạn vẫn muốn trở về danh sách?');" })
            </div>
        </div>
    </div>
}

BanHang/Views/LoaiSanPham/Index.cshtml
@model PagedList.IPagedList<Model.EF.LoaiSanPham>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Danh sách phân loại";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1 class="page-header">
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Tác vụ</a></li>
        <li class="active">@ViewBag.Title</li>
    </ol>
</section>

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-body">
                <div>
                    <a href="/LoaiSanPham/ThemMoi" class="btn bg-olive btn-lg" data-toggle="modal" data-target="#modal-themMoi" data-backdrop="static" data-keyboard="false">
                        Thêm Mới
                    </a>
                    <div class="modal fade " id="modal-themMoi">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="background-color:#80d6ff; font-size : 15px; text-align: center">Tên phân loại</th>
                            <th style="background-color:#80d6ff; font-size : 15px; text-align: center">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td style="padding-top: 12px; text-align: center">@item.TenLoai</td>
                                <td class="text-center">
                                    <a href="/LoaiSanPham/CapNhat/@item.MaLoaiSP" class="btn bg-maroon" style="border-radius:15px" data-toggle="modal" data-target="#modal-capNhat-@item.MaLoaiSP" data-backdrop="static" data-keyboard="false">Sửa</a>
                                    <div class="modal fade " id="modal-capNhat-@item.MaLoaiSP">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            </div>
                                        </div>
                                    </div>
                                    <a href="/LoaiSanPham/Xoa/@item.MaLoaiSP" class="btn bg-navy" style="border-radius:15px" data-toggle="modal" data-target="#modal-Xoa-@item.MaLoaiSP">Xóa</a>
                                    <div class="modal fade " id="modal-Xoa-@item.MaLoaiSP">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
    </div>
</div>

BanHang/Views/LoaiSanPham/ThemMoi.cshtml
@model Model.EF.LoaiSanPham

@{
    Layout = null;
}

@using (Html.BeginForm("ThemMoi", "LoaiSanPham", FormMethod.Post))
{
    <div class="modal-header bg-olive">
        <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Thêm phân loại sản phẩm</h4>
    </div>

    <div class="modal-body form-horizontal">

        @Html.AntiForgeryToken()
        <div class="form-group">
            <span class = "control-label col-md-4">Tên nhà cung cấp</span>
            <div class="col-md-6">
                @Html.DropDownList("MaNCC", null, "-- Chọn nhà cung cấp --", htmlAttributes: new { @class = "form-control", required = "required" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TenLoai, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.TextBoxFor(model => model.TenLoai, new { @class = "form-control", required = "required" })
            </div>
        </div>

        <div class="modal-footer">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn bg-olive btn-lg">Thêm Mới</button>
            </div>
        </div>
    </div>
}

BanHang/Views/LoaiSanPham/Xoa.cshtml
@model Model.EF.LoaiSanPham

@{
    Layout = null;
}


@using (Html.BeginForm("Xoa", "LoaiSanPham", FormMethod.Post))
{
    <div class="modal-header bg-navy">
        <h4 class="modal-title">Xóa phân loại</h4>
    </div>

    <div class="modal-body">
        <!-- form start -->
        @Html.AntiForgeryToken()       
        @Html.HiddenFor(model=>model.MaLoaiSP)
        <h4>Bạn có chắc muốn xoá phân loại này?</h4>
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-lg bg-navy">Xóa</button>
    </div>
}