BanHang/Controllers/BanHangController.cs
using BanHang.Models;
using Model.DAO;
using Model.EF;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class BanHangController : Controller
    {
        private string SanPham = "SanPham";
        OnlineShopDbContext db = new OnlineShopDbContext();
        // GET: BanHang
        public ActionResult Index(string search, int page = 1, int pagesize = 5)
        {
            var dao = new SanPhamDAO();
            var model = dao.ListAllPaging(search, page, pagesize);
            ViewBag.Search = search;
            return View(model);
        }

        [HttpGet]
        public ActionResult ThanhToan()
        {
            var thanhToan = Session[SanPham];
            var list = new List<ThanhToanSanPham>();
            if (thanhToan != null)
            {
                list = (List<ThanhToanSanPham>)thanhToan;
            }
            return View(list);
        }

        [HttpPost]
        public ActionResult ThanhToan(FormCollection collection)
        {
            var hoaDon = new HoaDon();
            var sanPhamDAO = new SanPhamDAO();
            var chiTietDao = new CTHD_DAO();

            hoaDon.NgayBan = DateTime.Now;
            hoaDon.TongSL = int.Parse(collection["TongSL"]);
            hoaDon.TongTien = decimal.Parse(collection["TongTien"]);
            hoaDon.MaNV = long.Parse(collection["MaNV"]);
            if (collection["MaKH"] == "")
            {
                hoaDon.MaKH = null;
            }
            else
            {
                hoaDon.MaKH = long.Parse(collection["MaKH"]);
            }

            var maHD = new HoaDonDAO().Insert(hoaDon);
            var thanhToan = (List<ThanhToanSanPham>)Session[SanPham];

            foreach (var item in thanhToan)
            {
                var chiTiet = new CTHD();
                chiTiet.MaSP = item.SanPham.MaSP;
                chiTiet.TenSP = item.SanPham.TenSP;
                chiTiet.MaHD = maHD;
                chiTiet.SoLuong = item.SoLuong;
                chiTiet.GiaBan = item.SanPham.GiaBan;
                chiTietDao.Insert(chiTiet);

                SanPham check = sanPhamDAO.ViewDetail(chiTiet.MaSP);
                check.SoLuong -= chiTiet.SoLuong;
                sanPhamDAO.CapNhatSoLuong(check);
            }
            thanhToan.Clear();


            return RedirectToAction("Index", "HoaDon");
        }

        public ActionResult ThemSanPham(long maSP, int soLuong)
        {
            var sanPham = new SanPhamDAO().ViewDetail(maSP);
            var thanhToan = Session[SanPham];
            if (thanhToan != null)
            {
                var list = (List<ThanhToanSanPham>)thanhToan;
                if (list.Exists(x => x.SanPham.MaSP == maSP))
                {
                    foreach (var item in list)
                    {
                        if (item.SanPham.MaSP == maSP)
                        {
                            item.SoLuong += soLuong;
                        }
                    }
                }
                else
                {
                    var item = new ThanhToanSanPham();
                    item.SanPham = sanPham;
                    item.SoLuong = soLuong;
                    list.Add(item);
                }
                Session[SanPham] = list;
            }
            else
            {
                var item = new ThanhToanSanPham();
                item.SanPham = sanPham;
                item.SoLuong = soLuong;
                var list = new List<ThanhToanSanPham>();
                list.Add(item);
                Session[SanPham] = list;

            }
            return RedirectToAction("Index");
        }

        public ActionResult Xoa(long maSP)
        {
            var thanhToan = Session[SanPham];
            if (thanhToan != null)
            {
                var list = (List<ThanhToanSanPham>)thanhToan;
                list.RemoveAll(x => x.SanPham.MaSP == maSP);

            }
            return RedirectToAction("ThanhToan");

        }

        public ActionResult XoaGioHang()
        {
            var thanhToan = Session[SanPham];
            if (thanhToan != null)
            {
                var list = (List<ThanhToanSanPham>)thanhToan;
                list.Clear();
            }
            return RedirectToAction("ThanhToan");

        }

        public ActionResult CapNhat(long maSP, FormCollection collection)
        {
            var thanhToan = Session[SanPham];
            if (thanhToan != null)
            {
                var list = (List<ThanhToanSanPham>)thanhToan;
                foreach (var item in list)
                {
                    if (item.SanPham.MaSP == maSP)
                    {
                        item.SoLuong = int.Parse(collection["soLuongMoi"].ToString());
                    }
                }
            }
            return RedirectToAction("ThanhToan");
        }
    }
}

BanHang/Controllers/HoaDonController.cs
using Model.DAO;
using Model.EF;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class HoaDonController : Controller
    {
        OnlineShopDbContext db = new OnlineShopDbContext();
        // GET: HoaDon
        [HttpGet]
        public ActionResult Index(string search, int page = 1, int pagesize = 10)
        {
            var dao = new HoaDonDAO();
            var model = dao.ListAllPaging(search, page, pagesize);
            ViewBag.Search = search;
            return View(model);
        }

        [HttpGet]
        public ActionResult ChiTietDonHang(long id)
        {
            ViewBag.CTHD = db.CTHDs.Where(x => x.MaHD == id);
            var donHang = new HoaDonDAO().ViewDetail(id);
            return View(donHang);
        }

        [HttpGet]
        public ActionResult InHoaDon(long id)
        {
            ViewBag.CTHD = db.CTHDs.Where(x => x.MaHD == id);
            var donHang = new HoaDonDAO().ViewDetail(id);
            return View(donHang);
        }

        [HttpGet]
        public ActionResult XoaHoaDon(long id)
        {
            var hoaDon = new HoaDonDAO().ViewDetail(id);
            return View(hoaDon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult XoaHoaDon(HoaDon hoaDon)
        {
            var dao = new HoaDonDAO();
            var id = dao.Delete(hoaDon);
            if (id)
                return RedirectToAction("Index");
            else
                return View();
        }

        public ActionResult Printf(int id)
        {
            var report = new ActionAsPdf("InHoaDon", new { id = id });
            return report;
        }
    }
}

BanHang/Controllers/NhanVienController.cs
using BanHang.Common;
using BanHang.Models;
using Model.DAO;
using Model.EF;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class NhanVienController : BaseController
    {
        // GET: NhanVien
        [KiemTraQuyen(MaChucNang = "Xem_NhanVien")]
        public ActionResult Index(string search, int page = 1, int pagesize = 10)
        {
            var dao = new NhanVienDAO();
            var model = dao.ListAllPaging(search, page, pagesize);
            ViewBag.Search = search;
            return View(model);
        }

        [HttpGet]
        public ActionResult ThemMoi()
        {
            return PartialView();
        }

        [HttpGet]
        public ActionResult CapNhat(long id)
        {
            var nhanVien = new NhanVienDAO().ViewDetail(id);
            return PartialView(nhanVien);
        }

        [HttpGet]
        public ActionResult Xoa(long id)
        {
            var nhanVien = new NhanVienDAO().ViewDetail(id);
            return PartialView(nhanVien);
        }

        [HttpGet]
        public ActionResult ThongTin(long id)
        {
            var nhanVien = new NhanVienDAO().ViewDetail(id);
            ViewBag.MaNV = nhanVien.MaNV;
            return View(nhanVien);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ThemMoi(NhanVien nhanVien, HttpPostedFileBase FileAnh)
        {

            OnlineShopDbContext db = new OnlineShopDbContext();
            string path = "";
            if (FileAnh != null && FileAnh.ContentLength > 0)
            {
                string extension = Path.GetExtension(FileAnh.FileName);
                if (extension.Equals(".jpg") || extension.Equals(".png") || extension.Equals(".jpeg"))
                {
                    path = Path.Combine(Server.MapPath("~/Image/NhanVien/"), FileAnh.FileName);
                    FileAnh.SaveAs(path);
                }
                nhanVien.HinhAnh = FileAnh.FileName;
                nhanVien.NgayThamGia = DateTime.Now;
                var encryptedMd5Pas = Encryptor.MD5Hash(nhanVien.MatKhau);
                nhanVien.MatKhau = encryptedMd5Pas;

                db.NhanViens.Add(nhanVien);
                db.SaveChanges();

                SetAlert("Thêm mới thành công", "success");
                return RedirectToAction("Index");
            }
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CapNhat(NhanVien nhanVien)
        {
            var dao = new NhanVienDAO();
            var id = dao.Update(nhanVien);
            if (id)
            {
                SetAlert("Cập nhật thành công", "error");
                return RedirectToAction("Index");
            }
            return View("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Xoa(NhanVien nhanVien)
        {
            var dao = new NhanVienDAO();
            var id = dao.Delete(nhanVien);
            if (id)
            {
                SetAlert("Xóa thành công", "error");
                return RedirectToAction("Index");
            }
            else
                return View();
        }

        public void Ds_NhanVien()
        {
            OnlineShopDbContext db = new OnlineShopDbContext();
            var model = db.NhanViens.ToList();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

            using (var Ep = new ExcelPackage(new FileInfo("NhanVien.xlsx")))
            {
                ExcelWorksheet Sheet = Ep.Workbook.Worksheets.Add("Report");
                Sheet.Cells["A1"].Value = "Mã NV";
                Sheet.Cells["B1"].Value = "Tên";
                Sheet.Cells["C1"].Value = "Giới tính";
                Sheet.Cells["D1"].Value = "Số CMND";
                Sheet.Cells["E1"].Value = "Ngày Sinh";
                Sheet.Cells["F1"].Value = "Số điện thoại";
                Sheet.Cells["G1"].Value = "Email";
                Sheet.Cells["H1"].Value = "Địa chỉ";
                Sheet.Cells["I1"].Value = "Chức vụ";
                Sheet.Cells["J1"].Value = "Mức lương";
                int row = 2;
                foreach (var item in model)
                {

                    Sheet.Cells[string.Format("A{0}", row)].Value = item.MaNV;
                    Sheet.Cells[string.Format("B{0}", row)].Value = item.TenNV;
                    Sheet.Cells[string.Format("C{0}", row)].Value = item.GioiTinh;
                    Sheet.Cells[string.Format("D{0}", row)].Value = item.SoCMND;
                    Sheet.Cells[string.Format("E{0}", row)].Value = item.NgaySinh;
                    Sheet.Cells[string.Format("F{0}", row)].Value = item.SoDT;
                    Sheet.Cells[string.Format("G{0}", row)].Value = item.Email;
                    Sheet.Cells[string.Format("H{0}", row)].Value = item.DiaChi;
                    Sheet.Cells[string.Format("I{0}", row)].Value = item.ChucVu;
                    Sheet.Cells[string.Format("J{0}", row)].Value = item.MucLuong;
                    row++;
                }


                Sheet.Cells["A:AZ"].AutoFitColumns();
                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment: filename=" + "NhanVien.xlsx");
                Response.BinaryWrite(Ep.GetAsByteArray());
                Response.End();
            }
        }
    }
}

BanHang/Controllers/TrangChuController.cs
using Model.EF;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHang.Controllers
{
    public class TrangChuController : Controller
    {
        OnlineShopDbContext db = new OnlineShopDbContext();

        public ActionResult Index()
        {
            var sanPham = db.SanPhams.Where(x => x.GiamGia == 0).Take(12).ToList();
            ViewBag.SanPham = db.SanPhams.Where(x => x.GiamGia > 0).Take(6).ToList();
            return View(sanPham);
        }


        // product details
        public ActionResult ChiTiet(long id)
        {
            var sanPham = db.SanPhams.Single(x => x.MaSP == id);
            ViewBag.ChiTiet = ListByCategoryId(sanPham.MaLoaiSP, 12);
            return View(sanPham);
        }

        public ActionResult SanPhamKhuyenMai()
        {
            var sanPham = db.SanPhams.Where(x => x.GiamGia > 0).ToList();
            return View(sanPham);
        }

        public ActionResult TatCaSanPham(int? page)
        {
            int pageSize = 18;
            int pageNum = (page ?? 1);

            var sanPham = db.SanPhams.ToList();
            return View(sanPham.ToPagedList(pageNum, pageSize));
        }

        public List<SanPham> ListByCategoryId(long? id, int count)
        {
            var sanPham = db.SanPhams.Where(x => x.MaLoaiSP == id).Take(count).ToList();

            return sanPham;
        }

        public ActionResult Menu()
        {
            var loaiSP = db.LoaiSanPhams.ToList();
            return PartialView(loaiSP);
        }

        // changed into the top 3 menu
        public ActionResult PhanLoaiSanPham(long id)
        {
            var sanPham = ListByCategoryId(id, 8);
            var loaiSP = db.LoaiSanPhams.Single(x => x.MaLoaiSP == id);
            ViewBag.LoaiSP = loaiSP.TenLoai;
            return View(sanPham);
        }

    }
}

BanHang/Views/Shared/_Error404.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <h1>Đây là mục của QUẢN LÝ</h1>
    </div>
</body>
</html>

BanHang/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title | Ministop</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/Assets/AdminLTE-2.4.18/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/AdminLTE-2.4.18/bower_components/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Assets/AdminLTE-2.4.18/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Assets/AdminLTE-2.4.18/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/Assets/AdminLTE-2.4.18/dist/css/skins/skin-blue.min.css">
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="@Url.Action("Index","Home")" class="logo">
                <span class="logo-mini"><b>H</b>N</span>
                <span class="logo-lg"><b>Ministop</span>
            </a>
            <nav class="navbar navbar-static-top position-relative" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"></a>
            </nav>

        </header>
        <aside class="main-sidebar">
            @Html.Partial("_SidebarParial")
        </aside>
        <div class="content-wrapper">
            <section class="content-header">
                @if (TempData["AlertMessage"] != null)
                {
                    <div id="AlertBox" class="alert @TempData["AlertType"]">
                        @TempData["AlertMessage"]
                    </div>
                }
                @RenderBody()
            </section>
            <section class="content container-fluid"></section>
        </div>
        <footer class="main-footer">
            <strong>Copyright &copy; 2020 <a href="https://www.facebook.com/vqhuyz" target="_blank">Vũ Quốc Huy</a>.</strong> All rights reserved.
        </footer>
    </div>

    <script src="~/Assets/AdminLTE-2.4.18/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="~/Assets/AdminLTE-2.4.18/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/Assets/AdminLTE-2.4.18/dist/js/adminlte.min.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.min.js"></script>
    <script>
        $('#AlertBox').removeClass('hide');
        $('#AlertBox').delay(1500).slideUp(500);
    </script>
</body>
</html> 

BanHang/Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Cửa hàng tiện lợi MiniStop</title>

    <link rel="stylesheet" href="~/Assets/Client/petshop/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Assets/Client/petshop/css/style.css">
    <link rel="stylesheet" href="~/Assets/Client/petshop/fontawesome/css/all.css">

    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Chewy&family=Open+Sans&family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap" rel="stylesheet">

    <!-- jquery -->
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>
    <div class="header">
        <div class="container">
            <div class="row top-info">

                <div class="col-sm-3 logo my-3">
                    <a href="/TrangChu">
                        <img src="~/Assets/Client/petshop/images/logo.png" alt="" class="rounded-circle p-2">
                        <span class="ml-3 font-weight-bold">
                            MiniStop
                        </span>
                    </a>
                </div>
                <!-- end logo -->

                <div class="col-sm-7 search mt-5 pl-4">
                    <form class="form-inline">
                        <input class="form-control mr-sm-2" type="search" placeholder="Tìm kiếm...">
                        <button class="btn btn-danger btn-search my-2 my-sm-0" type="submit">Tìm</button>
                    </form>
                </div>
                <!-- end search -->
                <!-- start contact -->
                <div class="col-sm-2 contact-info mt-4">
                    <div class="row">
                        <div class="col-sm-12 media">
                            <a href="https://www.facebook.com/vqhuyz" target="_blank" class="facebook mx-2"><i class="fab fa-facebook-square"></i></a>
                            <a href="https://www.instagram.com/vqhuyz/" target="_blank" class="insta mx-2"><i class="fab fa-instagram"></i></a>
                            <a href="#" class="pinterest mx-2"><i class="fab fa-pinterest-square"></i></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 basic-info">
                            <a href="#"><i class="fas fa-envelope"></i> vqhuyz@gmail.com</a>
                            <span><i class="fas fa-phone-alt"></i> 0828365961</span>
                        </div>
                    </div>
                    <!-- end contact -->
                </div>
                <!-- end contact info -->
            </div>
            <!-- end container -->
        </div>
        <!-- end top info -->
        <div class="navigation">
            <div class="container">
                <div class="row menu-bottom">
                    <nav class="navbar navbar-expand-lg navbar-light p-0">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavDropdown">
                            <ul class="navbar-nav font-weight-bold">
                                <li class="nav-item active mx-4">
                                    <a class="nav-link" href="/TrangChu"><i class="fas fa-home"></i><span class="sr-only">(current)</span></a>
                                </li>
                                <li class="nav-item mx-4">
                                    <a class="nav-link" href="#">Giới thiệu</a>
                                </li>
                                <li class="nav-item dropdown mx-4">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Sản phẩm
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        @Html.Action("Menu", "TrangChu")
                                    </div>
                                </li>
                                <li class="nav-item mx-4">
                                    <a class="nav-link" href="#">Danh sách cửa hàng</a>
                                </li>
                                <li class="nav-item mx-4">
                                    <a class="nav-link" href="#">Dịch vụ</a>
                                </li>
                                <li class="nav-item mx-4">
                                    <a class="nav-link" href="#">Liên hệ</a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                    <!-- end nav -->
                </div>
                <!-- end menu bottom -->
            </div>
            <!-- end container -->
        </div>
        <!-- end navigation -->
    </div>
    <!-- end header -->


    <div class="content-body py-3">

        <div class="container">
            @RenderBody()
        </div>

        <!-- cart noti -->
        <div class="cart-noti font-weight-bold  d-none">
            <i class="fas fa-check-circle text-info"></i>
            <span>Đã thêm vào giỏ hàng.</span>
        </div>

    </div>
    <!-- content body -->
    <!-- footer -->
    <div class="container-fluid bg-secondary text-white footer">
        <div class="row p-5">
            <div class="col-sm-4">
                <h4 class="text-uppercase border-bottom">MiniStop.vn</h4>
                <div><b>Địa chỉ:</b> 310 Trần Hưng Đạo, Phường Đông Hòa B, Thị Xã Dĩ An, Tỉnh Bình Dương.</div>
                <div><b>Phone:</b> 0828365961</div>
                <div><b>Email:</b> vqhuyz@gmail.com</div>
            </div>
            <div class="col-sm-4">
                <h4 class="text-uppercase border-bottom">Giới thiệu</h4>
                <a href="#" class="text-white d-block">Về chúng tôi</a>
                <a href="#" class="text-white">Bài viết</a>
            </div>
            <div class="col-sm-4">
                <h4 class="text-uppercase border-bottom">Chính sách</h4>
                <a href="#" class="text-white d-block">Đổi trả</a>
                <a href="#" class="text-white">Thanh toán</a>
            </div>
        </div>
        <div class="row bg-light">
            <div class="col-sm-12 text-uppercase text-dark text-center">
                &copy; công ty tnhh ministop việt nam
            </div>
        </div>
    </div>

    <!-- end footer -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="~/Assets/Client/petshop/bootstrap/js/jquery-3.3.1.slim.min.js"></script>
    <script src="~/Assets/Client/petshop/bootstrap/js/popper.min.js"></script>
    <script src="~/Assets/Client/petshop/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/Assets/Client/petshop/js/script.js"></script>

BanHang/Views/Shared/_SidebarParial.cshtml
<section class="sidebar">
   
    <!-- Sidebar user panel (optional) -->
    @{
        var session = (Model.EF.NhanVien)Session[BanHang.Common.CommonConstant.USER_SESSION];
    }
    @if (session != null)
    {
        <div class="user-panel">
            <div class="pull-left image">
                <img width="75" height="75" src="~/Image/NhanVien/@session.HinhAnh" class="img-circle" alt="@session.TenNV">
            </div>
            <div class="pull-left info">
                <p>@session.TenNV</p>
                <a href="@Url.Action("Index","Home")"><i class="fa fa-circle text-success"></i> @session.TaiKhoan</a>
            </div>
        </div>
    }

    <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">NHÂN VIÊN</li>
            <!-- Optionally, you can add icons to the links -->
            <li>
                <a href="@Url.Action("Index","BanHang")">
                    <i class="fa fa-shopping-cart"></i> <span>Bán Hàng</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("ThanhToan","BanHang",session)">
                    <i class="fa fa-dollar"></i> <span>Thanh toán</span>
                </a>
            </li>
            <li id="orders">
                <a href="@Url.Action("Index","HoaDon")">
                    <i class="fa fa-book"></i>
                    <span>Hóa Đơn</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("ThemMoi","SanPham")">
                    <i class="fa fa-plus"></i> <span>Thêm Sản Phẩm</span>
                </a>
            </li>
            <li id="customers">
                <a href="@Url.Action("Index","KhachHang")">
                    <i class="fa fa-users"></i> <span>Khách Hàng</span>
                </a>
            </li>
            <li class="header" >QUẢN LÝ</li>
            <li id="customers">
                <a href="@Url.Action("Index","NhanVien")">
                    <i class="fa fa-user"></i> <span>Nhân Viên</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","NhaCungCap")">
                    <i class="fa fa-user-secret"></i> <span>Nhà Cung Cấp</span>
                </a>
            </li>
            <li id="products">
                <a href="@Url.Action("Index","SanPham")">
                    <i class="fa fa-shopping-basket"></i>
                    <span>Sản Phẩm</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","LoaiSanPham")">
                    <i class="fa fa-cubes"></i> <span>Phân Loại Sản Phẩm</span>
                </a>
            </li>
            <li class="header" >QUẢN LÝ CÁ NHÂN</li>
            <li>
                <a href="@Url.Action("Index","ThongTinCaNhan", session)">
                    <i class="fa fa-user"></i> <span>Hồ Sơ Cá Nhân</span>
                </a>
            </li>
            <li>
                <a href="@Url.Action("Logout","Login")" onclick="return confirm('Bạn đang tiến hành đăng xuất khỏi tài khoản');">
                    <i class="fa fa-sign-out"></i> <span>Đăng xuất</span>
                </a>
            </li>

        </ul>
    <!-- /.sidebar-menu -->
</section>